/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TournamentDetailRouteImport } from './routes/tournament-detail'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomHubRouteImport } from './routes/room-hub'
import { Route as ModeratorsRouteImport } from './routes/moderators'
import { Route as MatchControlRouteImport } from './routes/match-control'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateTournamentRouteImport } from './routes/create-tournament'
import { Route as BracketsRouteImport } from './routes/brackets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyTeamTeamIdRouteImport } from './routes/verify-team.$teamId'
import { Route as TournamentDetailTournamentIdRouteImport } from './routes/tournament-detail/$tournamentId'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentDetailRoute = TournamentDetailRouteImport.update({
  id: '/tournament-detail',
  path: '/tournament-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomHubRoute = RoomHubRouteImport.update({
  id: '/room-hub',
  path: '/room-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorsRoute = ModeratorsRouteImport.update({
  id: '/moderators',
  path: '/moderators',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchControlRoute = MatchControlRouteImport.update({
  id: '/match-control',
  path: '/match-control',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTournamentRoute = CreateTournamentRouteImport.update({
  id: '/create-tournament',
  path: '/create-tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketsRoute = BracketsRouteImport.update({
  id: '/brackets',
  path: '/brackets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTeamTeamIdRoute = VerifyTeamTeamIdRouteImport.update({
  id: '/verify-team/$teamId',
  path: '/verify-team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentDetailTournamentIdRoute =
  TournamentDetailTournamentIdRouteImport.update({
    id: '/$tournamentId',
    path: '/$tournamentId',
    getParentRoute: () => TournamentDetailRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brackets': typeof BracketsRoute
  '/create-tournament': typeof CreateTournamentRoute
  '/dashboard': typeof DashboardRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/match-control': typeof MatchControlRoute
  '/moderators': typeof ModeratorsRoute
  '/room-hub': typeof RoomHubRoute
  '/settings': typeof SettingsRoute
  '/stream': typeof StreamRoute
  '/tournament-detail': typeof TournamentDetailRouteWithChildren
  '/tournaments': typeof TournamentsRoute
  '/tournament-detail/$tournamentId': typeof TournamentDetailTournamentIdRoute
  '/verify-team/$teamId': typeof VerifyTeamTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brackets': typeof BracketsRoute
  '/create-tournament': typeof CreateTournamentRoute
  '/dashboard': typeof DashboardRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/match-control': typeof MatchControlRoute
  '/moderators': typeof ModeratorsRoute
  '/room-hub': typeof RoomHubRoute
  '/settings': typeof SettingsRoute
  '/stream': typeof StreamRoute
  '/tournament-detail': typeof TournamentDetailRouteWithChildren
  '/tournaments': typeof TournamentsRoute
  '/tournament-detail/$tournamentId': typeof TournamentDetailTournamentIdRoute
  '/verify-team/$teamId': typeof VerifyTeamTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brackets': typeof BracketsRoute
  '/create-tournament': typeof CreateTournamentRoute
  '/dashboard': typeof DashboardRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/match-control': typeof MatchControlRoute
  '/moderators': typeof ModeratorsRoute
  '/room-hub': typeof RoomHubRoute
  '/settings': typeof SettingsRoute
  '/stream': typeof StreamRoute
  '/tournament-detail': typeof TournamentDetailRouteWithChildren
  '/tournaments': typeof TournamentsRoute
  '/tournament-detail/$tournamentId': typeof TournamentDetailTournamentIdRoute
  '/verify-team/$teamId': typeof VerifyTeamTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brackets'
    | '/create-tournament'
    | '/dashboard'
    | '/hall-of-fame'
    | '/match-control'
    | '/moderators'
    | '/room-hub'
    | '/settings'
    | '/stream'
    | '/tournament-detail'
    | '/tournaments'
    | '/tournament-detail/$tournamentId'
    | '/verify-team/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brackets'
    | '/create-tournament'
    | '/dashboard'
    | '/hall-of-fame'
    | '/match-control'
    | '/moderators'
    | '/room-hub'
    | '/settings'
    | '/stream'
    | '/tournament-detail'
    | '/tournaments'
    | '/tournament-detail/$tournamentId'
    | '/verify-team/$teamId'
  id:
    | '__root__'
    | '/'
    | '/brackets'
    | '/create-tournament'
    | '/dashboard'
    | '/hall-of-fame'
    | '/match-control'
    | '/moderators'
    | '/room-hub'
    | '/settings'
    | '/stream'
    | '/tournament-detail'
    | '/tournaments'
    | '/tournament-detail/$tournamentId'
    | '/verify-team/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BracketsRoute: typeof BracketsRoute
  CreateTournamentRoute: typeof CreateTournamentRoute
  DashboardRoute: typeof DashboardRoute
  HallOfFameRoute: typeof HallOfFameRoute
  MatchControlRoute: typeof MatchControlRoute
  ModeratorsRoute: typeof ModeratorsRoute
  RoomHubRoute: typeof RoomHubRoute
  SettingsRoute: typeof SettingsRoute
  StreamRoute: typeof StreamRoute
  TournamentDetailRoute: typeof TournamentDetailRouteWithChildren
  TournamentsRoute: typeof TournamentsRoute
  VerifyTeamTeamIdRoute: typeof VerifyTeamTeamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament-detail': {
      id: '/tournament-detail'
      path: '/tournament-detail'
      fullPath: '/tournament-detail'
      preLoaderRoute: typeof TournamentDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-hub': {
      id: '/room-hub'
      path: '/room-hub'
      fullPath: '/room-hub'
      preLoaderRoute: typeof RoomHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderators': {
      id: '/moderators'
      path: '/moderators'
      fullPath: '/moderators'
      preLoaderRoute: typeof ModeratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-control': {
      id: '/match-control'
      path: '/match-control'
      fullPath: '/match-control'
      preLoaderRoute: typeof MatchControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-tournament': {
      id: '/create-tournament'
      path: '/create-tournament'
      fullPath: '/create-tournament'
      preLoaderRoute: typeof CreateTournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brackets': {
      id: '/brackets'
      path: '/brackets'
      fullPath: '/brackets'
      preLoaderRoute: typeof BracketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-team/$teamId': {
      id: '/verify-team/$teamId'
      path: '/verify-team/$teamId'
      fullPath: '/verify-team/$teamId'
      preLoaderRoute: typeof VerifyTeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament-detail/$tournamentId': {
      id: '/tournament-detail/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/tournament-detail/$tournamentId'
      preLoaderRoute: typeof TournamentDetailTournamentIdRouteImport
      parentRoute: typeof TournamentDetailRoute
    }
  }
}

interface TournamentDetailRouteChildren {
  TournamentDetailTournamentIdRoute: typeof TournamentDetailTournamentIdRoute
}

const TournamentDetailRouteChildren: TournamentDetailRouteChildren = {
  TournamentDetailTournamentIdRoute: TournamentDetailTournamentIdRoute,
}

const TournamentDetailRouteWithChildren =
  TournamentDetailRoute._addFileChildren(TournamentDetailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BracketsRoute: BracketsRoute,
  CreateTournamentRoute: CreateTournamentRoute,
  DashboardRoute: DashboardRoute,
  HallOfFameRoute: HallOfFameRoute,
  MatchControlRoute: MatchControlRoute,
  ModeratorsRoute: ModeratorsRoute,
  RoomHubRoute: RoomHubRoute,
  SettingsRoute: SettingsRoute,
  StreamRoute: StreamRoute,
  TournamentDetailRoute: TournamentDetailRouteWithChildren,
  TournamentsRoute: TournamentsRoute,
  VerifyTeamTeamIdRoute: VerifyTeamTeamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
